"""empty message

Revision ID: 0a01d715af0f
Revises: 5d1f9f3559c6
Create Date: 2025-06-05 14:02:00.173203

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '0a01d715af0f'
down_revision = '5d1f9f3559c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    # ### end Alembic commands ###
