"""add thumbnail

Revision ID: 15a65f92442b
Revises: ce99dd99aca3
Create Date: 2026-02-05 21:20:24.468307

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '15a65f92442b'
down_revision = 'ce99dd99aca3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'thumbnail_path')
    # ### end Alembic commands ###
