"""Added file hash

Revision ID: 26060566ea30
Revises: ea7b26c224c2
Create Date: 2026-01-12 20:12:40.874662

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '26060566ea30'
down_revision = 'ea7b26c224c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False))
    op.create_index(op.f('ix_file_content_hash'), 'file', ['content_hash'], unique=False)
    op.create_unique_constraint('unique_user_file_content', 'file', ['owner_id', 'content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_file_content', 'file', type_='unique')
    op.drop_index(op.f('ix_file_content_hash'), table_name='file')
    op.drop_column('file', 'content_hash')
    # ### end Alembic commands ###
