"""add page count to material

Revision ID: 3d9d6cd3ce57
Revises: 7d079f02efe1
Create Date: 2026-01-16 17:36:11.499485

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3d9d6cd3ce57'
down_revision = '7d079f02efe1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('page_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'page_count')
    # ### end Alembic commands ###
