"""empty message

Revision ID: 5291e64bb969
Revises: 78f9a097b289
Create Date: 2025-06-05 14:15:29.141898

"""


# revision identifiers, used by Alembic.
revision = '5291e64bb969'
down_revision = '78f9a097b289'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
