"""add user read

Revision ID: 5dfab6995755
Revises: b2c3d4e5f6a7
Create Date: 2026-02-08 12:26:11.530592

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5dfab6995755'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('terms_accepted', sa.Boolean(), nullable=True))
    op.execute("UPDATE \"user\" SET terms_accepted = TRUE")
    op.alter_column('user', 'terms_accepted', nullable=False)

    op.add_column('user', sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE \"user\" SET terms_accepted_at = NOW()")

    op.add_column('user', sa.Column('marketing_accepted', sa.Boolean(), nullable=True))
    op.execute("UPDATE \"user\" SET marketing_accepted = FALSE")
    op.alter_column('user', 'marketing_accepted', nullable=False)

    op.add_column('user', sa.Column('marketing_accepted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'marketing_accepted_at')
    op.drop_column('user', 'marketing_accepted')
    op.drop_column('user', 'terms_accepted_at')
    op.drop_column('user', 'terms_accepted')
    # ### end Alembic commands ###
