"""add_cascade_delete_and_user_cleanup

Revision ID: 6be7b54f6b92
Revises: 5dfab6995755
Create Date: 2026-02-08 15:04:54.369178

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6be7b54f6b92'
down_revision = '5dfab6995755'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('file_owner_id_fkey'), 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('job_owner_id_fkey'), 'job', type_='foreignkey')
    op.create_foreign_key(None, 'job', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('material_file_id_fkey'), 'material', type_='foreignkey')
    op.drop_constraint(op.f('material_owner_id_fkey'), 'material', type_='foreignkey')
    op.create_foreign_key(None, 'material', 'file', ['file_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'material', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('ocr_cache_user_id_fkey'), 'ocr_cache', type_='foreignkey')
    op.create_foreign_key(None, 'ocr_cache', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('support_tickets_user_id_fkey'), 'support_tickets', type_='foreignkey')
    op.create_foreign_key(None, 'support_tickets', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('system_notifications_recipient_id_fkey'), 'system_notifications', type_='foreignkey')
    op.create_foreign_key(None, 'system_notifications', 'user', ['recipient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_read_notifications_notification_id_fkey'), 'user_read_notifications', type_='foreignkey')
    op.drop_constraint(op.f('user_read_notifications_user_id_fkey'), 'user_read_notifications', type_='foreignkey')
    op.create_foreign_key(None, 'user_read_notifications', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_read_notifications', 'system_notifications', ['notification_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_read_notifications', type_='foreignkey')
    op.drop_constraint(None, 'user_read_notifications', type_='foreignkey')
    op.create_foreign_key(op.f('user_read_notifications_user_id_fkey'), 'user_read_notifications', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_read_notifications_notification_id_fkey'), 'user_read_notifications', 'system_notifications', ['notification_id'], ['id'])
    op.drop_constraint(None, 'system_notifications', type_='foreignkey')
    op.create_foreign_key(op.f('system_notifications_recipient_id_fkey'), 'system_notifications', 'user', ['recipient_id'], ['id'])
    op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    op.create_foreign_key(op.f('support_tickets_user_id_fkey'), 'support_tickets', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'ocr_cache', type_='foreignkey')
    op.create_foreign_key(op.f('ocr_cache_user_id_fkey'), 'ocr_cache', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'material', type_='foreignkey')
    op.drop_constraint(None, 'material', type_='foreignkey')
    op.create_foreign_key(op.f('material_owner_id_fkey'), 'material', 'user', ['owner_id'], ['id'])
    op.create_foreign_key(op.f('material_file_id_fkey'), 'material', 'file', ['file_id'], ['id'])
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_foreign_key(op.f('job_owner_id_fkey'), 'job', 'user', ['owner_id'], ['id'])
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key(op.f('file_owner_id_fkey'), 'file', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
