"""empty message

Revision ID: 78f9a097b289
Revises: 0a01d715af0f
Create Date: 2025-06-05 14:03:56.170031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f9a097b289'
down_revision = '0a01d715af0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
