"""add ocr and pdf cache

Revision ID: 7d079f02efe1
Revises: 13f5e4ea00e2
Create Date: 2026-01-15 18:54:36.718280

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7d079f02efe1'
down_revision = '13f5e4ea00e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('ocr_options_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('pipeline_version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('result_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cache_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_cache_cache_key'), 'ocr_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_ocr_cache_created_at'), 'ocr_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_ocr_cache_file_hash'), 'ocr_cache', ['file_hash'], unique=False)
    op.create_index(op.f('ix_ocr_cache_ocr_options_hash'), 'ocr_cache', ['ocr_options_hash'], unique=False)
    op.create_index(op.f('ix_ocr_cache_user_id'), 'ocr_cache', ['user_id'], unique=False)
    op.create_table('pdf_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('config_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('template_version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('stored_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdf_exports_cache_key'), 'pdf_exports', ['cache_key'], unique=True)
    op.create_index(op.f('ix_pdf_exports_config_hash'), 'pdf_exports', ['config_hash'], unique=False)
    op.create_index(op.f('ix_pdf_exports_created_at'), 'pdf_exports', ['created_at'], unique=False)
    op.create_index(op.f('ix_pdf_exports_test_id'), 'pdf_exports', ['test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pdf_exports_test_id'), table_name='pdf_exports')
    op.drop_index(op.f('ix_pdf_exports_created_at'), table_name='pdf_exports')
    op.drop_index(op.f('ix_pdf_exports_config_hash'), table_name='pdf_exports')
    op.drop_index(op.f('ix_pdf_exports_cache_key'), table_name='pdf_exports')
    op.drop_table('pdf_exports')
    op.drop_index(op.f('ix_ocr_cache_user_id'), table_name='ocr_cache')
    op.drop_index(op.f('ix_ocr_cache_ocr_options_hash'), table_name='ocr_cache')
    op.drop_index(op.f('ix_ocr_cache_file_hash'), table_name='ocr_cache')
    op.drop_index(op.f('ix_ocr_cache_created_at'), table_name='ocr_cache')
    op.drop_index(op.f('ix_ocr_cache_cache_key'), table_name='ocr_cache')
    op.drop_table('ocr_cache')
    # ### end Alembic commands ###
