"""questions sort by id

Revision ID: bd5fa56f32dd
Revises: 51acd0300351
Create Date: 2025-11-30 20:26:32.746500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5fa56f32dd'
down_revision = '51acd0300351'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
