"""add new pipeline

Revision ID: ce99dd99aca3
Revises: 3d9d6cd3ce57
Create Date: 2026-01-17 17:08:44.145732

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce99dd99aca3'
down_revision = '3d9d6cd3ce57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    postgresql.ENUM('pending', 'done', 'failed', name='analysisstatus').create(op.get_bind())
    postgresql.ENUM('fast', 'reasoning', name='routingtier').create(op.get_bind())
    op.add_column('material', sa.Column('analysis_status', sa.Enum('pending', 'done', 'failed', name='analysisstatus'), nullable=False, server_default='pending'))
    op.add_column('material', sa.Column('routing_tier', sa.Enum('fast', 'reasoning', name='routingtier'), nullable=True))
    op.add_column('material', sa.Column('analysis_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('material', sa.Column('markdown_twin', sa.Text(), nullable=True))
    op.create_index(op.f('ix_material_analysis_status'), 'material', ['analysis_status'], unique=False)
    op.create_index(op.f('ix_material_routing_tier'), 'material', ['routing_tier'], unique=False)
    op.add_column('question', sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'citations')
    op.drop_index(op.f('ix_material_routing_tier'), table_name='material')
    op.drop_index(op.f('ix_material_analysis_status'), table_name='material')
    op.drop_column('material', 'markdown_twin')
    op.drop_column('material', 'analysis_version')
    op.drop_column('material', 'routing_tier')
    op.drop_column('material', 'analysis_status')

    postgresql.ENUM('pending', 'done', 'failed', name='analysisstatus').drop(op.get_bind())
    postgresql.ENUM('fast', 'reasoning', name='routingtier').drop(op.get_bind())
    # ### end Alembic commands ###
